export enum ErrorCodes {
  TITLE_TOO_SHORT = "CERTIFICATION/TITLE_TOO_SHORT",
  TITLE_TOO_LONG = "CERTIFICATION/TITLE_TOO_LONG",
  LEVEL_INVALID = "CERTIFICATION/LEVEL_INVALID",
  ID_EMPTY = "CERTIFICATION/ID_EMPTY",
  ID_INVALID = "CERTIFICATION/ID_INVALID",
}
